require("plugins.plugins-setup")

require("core.options")
require("core.chinese")
require("core.keymaps")
require("core.builtin-keys")
require("plugins.which-key")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.smear-cursor")

require("plugins.noice")
require("plugins.dashboard")
require("plugins.render-markdown")
require("plugins.indent-blankline")
require("plugins.aerial")
require("plugins.gitsigns")
